// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
<<<<<<< HEAD
    AppNav: typeof import('./components/AppNav.vue')['default']
    AppResult: typeof import('./components/AppResult.vue')['default']
    AppSearch: typeof import('./components/AppSearch.vue')['default']
=======
    AppModal: typeof import('./components/AppModal.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    AppTimer: typeof import('./components/AppTimer.vue')['default']
>>>>>>> 758e20fb8a5b0e6bcded8f413d2b39ec4d042f5f
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
